### ISSUE TITLE
Sync Category/Product Images

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#1]
Here are the steps to reproduce this issue. 

Go to **/media/catalog** folder and delete **category** folder. The idea is not having this folder. Now press on [Sync Category Images] button. Browser page reloads with the warning bellow:

```
Warning: scandir(/home/mydomain/public_html/media/catalog/category): failed to open dir: No such file or directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php on line 49

#0 [internal function]: mageCoreErrorHandler(2, 'scandir(/home/m...', '/home/mydomain/p...', 49, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(49): scandir('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->synccategoryAction()
#3 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('synccategory')
#4 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#6 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#7 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#8 {main}
```

A small change in the script is needed if folder /media/catalog/category doesn't exist. This should be done also for other folders that the extension is using like /media/catalog/**product**. By pressing the buttons it will be no warnings in pages.

**Comment by addison74** [comment]
If you rename /media/catalog/**product** and press again [Sync Product Images] you will get the following warning: 

```
Warning: scandir(/home/mydomain/public_html/media/catalog/product): failed to open dir: No such file or directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php on line 28

#0 [internal function]: mageCoreErrorHandler(2, 'scandir(/home/m...', '/home/mydomain/p...', 28, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(28): scandir('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(87): Fballiano_ImageCleaner_Helper_Data->scandirRecursive('/home/mydomain/p...')
#3 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->syncproductAction()
#4 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('syncproduct')
#5 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#7 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#8 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#9 {main}
```

**Comment by fballiano** [comment]
checks added for category, product and wysiwyg folders, thanks for the suggestion!
