### ISSUE TITLE
Sync WYSIWYG

### ISSUE THREAD

**Issue by addison74** [fballiano/openmage-image-cleaner#2]
I pushed [Sync WYSIWYG] button and the page loaded with the following warning:

```
Warning: scandir(/home/mydomain/public_html/skin/frontend/base/default/aw_zblocks/js/slider.js): failed to open dir: Not a directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php on line 66

#0 [internal function]: mageCoreErrorHandler(2, 'scandir(/home/m...', '/home/mydomain/p...', 66, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(66): scandir('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#3 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#4 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#5 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#6 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#7 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(56): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#8 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(117): Fballiano_ImageCleaner_Helper_Data->getAllCSSFilesContents()
#9 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->syncwysiwygAction()
#10 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('syncwysiwyg')
#11 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#13 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#14 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#15 {main}
```

This path **/home/mydomain/public_html/skin/frontend/base/default/aw_zblocks/js/slider.js** exits and the file has the right permissions.

I deleted this file and reload the page. A new warning was generated:

```
Warning: scandir(/home/mydomain/public_html/skin/frontend/base/default/favicon.ico): failed to open dir: Not a directory  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php on line 66

#0 [internal function]: mageCoreErrorHandler(2, 'scandir(/home/m...', '/home/mydomain/p...', 66, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(66): scandir('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#3 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#4 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#5 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(56): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#6 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(117): Fballiano_ImageCleaner_Helper_Data->getAllCSSFilesContents()
#7 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->syncwysiwygAction()
#8 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('syncwysiwyg')
#9 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#12 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#13 {main}
```

I removed one by one all the files reported in warnings. Now here is the final warning:

```
Notice: Undefined variable: result  in /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php on line 79

#0 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(79): mageCoreErrorHandler(8, 'Undefined varia...', '/home/mydomain/p...', 79, Array)
#1 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#2 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#3 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#4 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(74): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#5 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/Helper/Data.php(56): Fballiano_ImageCleaner_Helper_Data->getAllCSSFiles('/home/mydomain/p...')
#6 /home/mydomain/public_html/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(117): Fballiano_ImageCleaner_Helper_Data->getAllCSSFilesContents()
#7 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->syncwysiwygAction()
#8 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('syncwysiwyg')
#9 /home/mydomain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/mydomain/public_html/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/mydomain/public_html/app/Mage.php(729): Mage_Core_Model_App->run(Array)
#12 /home/mydomain/public_html/index.php(78): Mage::run('', 'store')
#13 {main}
```

As I understand this feature **Sync WYSIWYG** should check /media/wysiwyg folder and if it finds an image not used in any place will report it. But as you may see the extension is looking in other folders as reported before.

As a personal opinion this feature should be removed because the images from /media/wysiwyg are very hard to be identified where they are used. They could be in many places like CMS pages, Blocks, Product Description.

**Comment by addison74** [comment]
I forgot to mention /media/wysiwyg folder content can be checked in Magento Backend. Anyone can delete folders and images manually. But for products and categories it is a little bit complicated.

**Comment by fballiano** [comment]
problems should be fixed, thanks for the report!

I know that wysiwyg can be managed by the backend, but in my 11 years with magento nobody does (cause they're worried about deleting used images/files) so it grows without limits, that's why I'm trying to write this feature.

**Comment by addison74** [comment]
We must continue testing this feature. Have you considered using images in blocks, product description or elsewhere than CMS pages? In the case of products and categories, things are clear, but here once an image is deleted there is a risk of missing it in a page in the frontend. If someone uses a block-based extension like Aheadworks Z-Blocks and put his images in this folder he will have a problem if not revising the images and doing a mass delete action. 

You can evaluate all places where images are used but for Magento only and provide a warning in extension page about this issue.

**Comment by fballiano** [comment]
As written in the README I check images in:
- cms_block
- cms_pages
- core_email_templates
- all CSS files in /skin
because I need to avoid false positives as much as possible (that's the problem I always had with other extensions)..

about custom extensions, we'll never be able to support all of them, btw I hope they don't just use media/wysiwyg but instead they use media/extensionname or something like that.

we can try to support some of them but it will never be complete. at the same time, you could reference a product image in a static block... that condition will never be detected by any extension like this one, it would really become too difficult.

on my customers' stores I'd never "auto clean" WYSYWYG but I'd use the feature just as a double check to clear very old stuff (actually maybe it would be nice to show the filedate) because it will never be 100% safe (but neither the product/category ones although I also check custom EAV attributes and not only system ones).

hope I didn't forget anything :-)
