### ISSUE TITLE
error in sync products cache

### ISSUE THREAD

**Issue by empiricompany** [fballiano/openmage-image-cleaner#20]
I have executed the following steps in this order:

- Sync product cache
- Sync categories
- Sync products cache

The last step of synchronizing the products cache returned this error:

 ```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '-4-1/image/600x/17f82f742ffe127f42dca9de82fb58b1/l/e/letto-matri' for key 'entity_type_id', query was: INSERT INTO `fb_imagecleaner_image` (`entity_type_id`, `path`) VALUES (?, ?)
#0 /var/www/xxxxxxx/htdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(104): Zend_Db_Statement_Pdo->_execute()
#1 /var/www/xxxxxxx/htdocs/app/code/core/Zend/Db/Statement.php(289): Varien_Db_Statement_Pdo_Mysql->_execute()
#2 /var/www/xxxxxxx/htdocs/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#3 /var/www/xxxxxxx/htdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /var/www/xxxxxxx/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(492): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /var/www/xxxxxxx/htdocs/lib/Zend/Db/Adapter/Abstract.php(576): Varien_Db_Adapter_Pdo_Mysql->query()
#6 /var/www/xxxxxxx/htdocs/.modman/openmage-image-cleaner/app/code/community/Fballiano/ImageCleaner/controllers/Adminhtml/FbimagecleanerController.php(164): Zend_Db_Adapter_Abstract->insert()
#7 /var/www/xxxxxxx/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(428): Fballiano_ImageCleaner_Adminhtml_FbimagecleanerController->syncproductCacheAction()
#8 /var/www/xxxxxxx/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch()
#9 /var/www/xxxxxxx/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(188): Mage_Core_Controller_Varien_Router_Standard->match()
#10 /var/www/xxxxxxx/htdocs/app/code/core/Mage/Core/Model/App.php(371): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/xxxxxxx/htdocs/app/Mage.php(735): Mage_Core_Model_App->run()
#12 /var/www/xxxxxxx/htdocs/index.php(83): Mage::run()
```

there is no entry in fb_imagecleaner_image table with this path value (maybe in the stack trace is truncated?):
image/600x/17f82f742ffe127f42dca9de82fb58b1/l/e/letto-matri

i have this contains:
![contains](https://github.com/fballiano/openmage-image-cleaner/assets/5071467/5af49864-2c72-4105-9834-312b87bbec19)

php 7.4
openmage 19.4.21

**Comment by fballiano** [comment]
@empiricompany do you still have this error?
